### ISSUE TITLE
In .Net 6 getting view was not found when on new and existing project

### ISSUE THREAD

**Issue by ArjunVachhani** [dotnet/razor-compiler#225]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have one Web API project, After some time I need some MVC controller and Views, I added controller and views and modified startup to use `AddControllersWithViews` instead of `AddControllers`.  I am gettting Views was not found.

I also noticed that <proj>.views.dll is not generated on build/publish.
If I use runtime view compilation then I am not getting that error.

### Expected Behavior

It should load appropriate view and render it.

### Steps To Reproduce

Steps to reproduce,
1) Create a new ASP.Net 6 Web Api project
2) Add MVC controller and Views,
3) Navigate to controller action path.

### Exceptions (if any)

System.InvalidOperationException: The view 'Index' was not found. The following locations were searched:
/Views/Foobar/Index.cshtml
/Views/Shared/Index.cshtml
   at Microsoft.AspNetCore.Mvc.ViewEngines.ViewEngineResult.EnsureSuccessful(IEnumerable`1 originalLocations)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewResultExecutor.ExecuteAsync(ActionContext context, ViewResult result)
   at Microsoft.AspNetCore.Mvc.ViewResult.ExecuteResultAsync(ActionContext context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|30_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

### .NET Version

6

**Comment by jaredpar** [comment]
@chsienki this does look like a dupe. Can you confirm?

**Comment by chsienki** [comment]
Yeah, this looks like an SDK / VS Version mismatch which was addressed by https://github.com/dotnet/sdk/pull/24562.

@ArjunVachhani Can you try upgrading your SDK to 6.0.300 and see if the issue still happens inside VS?

**Comment by ArjunVachhani** [comment]
@chsienki where can I find 6.0.300 SDK? I can not find that on https://dotnet.microsoft.com/en-us/download/dotnet/6.0
I have latest SDK 6.0.202

**Comment by chsienki** [comment]
@ArjunVachhani Ah, I thought it was out already, but isn't quite yet. You can get it from https://dotnetbuilds.azureedge.net/public/Sdk/6.0.301-rtm.22254.17/dotnet-sdk-6.0.301-win-x64.exe

**Comment by ArjunVachhani** [comment]
@chsienki it is working with 6.0.300 SDK. 
Thank you @jaredpar @chsienki @javiercn @mkArtakMSFT
